name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for consistent tagging

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: index.docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository_name }}:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository_name }}:latest

      - name: Image details
        run: |
          echo "Pushed image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository_name }}:${{ github.sha }}"
          echo "Pushed image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository_name }}:latest"
